Repository prabhat7k/Hactoberfest22, pull requests merged in 2022-10, with the labels that each got.

#13 Added Spell-checker
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added tpt7k contributer
  Contributing.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#20 Added Anurag contributor
  Contributing.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#21 Added akhilender-bongirwar contributor
  Contributing.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#28 completed sentences in about.js
  src/components/About.js
Labels: documentation

#33 ADD: contributing guidelines
  Contributing.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted
